name: Deploy on merge to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH and deploy
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 82.25.119.112 >> ~/.ssh/known_hosts

        ssh root@82.25.119.112 << 'EOF'
          cd /home/EventCulture
          git pull origin main
          cd frontend && npm install && npm run build
          pm2 restart back-eventculture
        EOF
